### ISSUE TITLE
 Very Slow

### ISSUE THREAD

**Issue by pritishyuvraj** [asaini/Apriori#12]
I gave a database of 22 MB. It took around 600sec to solve it. Is this expected? Are there any other implementation in Python of Apriori by which execution time can be brought under 20sec? 
Also, can you give me a rough estimate of how much it will take to solve a database of 10MB, 15MB, 20MB using the best possible Apriori implementation in Python.

**Comment by sn1p3r46** [comment]
I guess the problem is python and its high level structures, try with pypy, but if you want a super speed program you can try this C implementation http://www.borgelt.net/apriori.html
Moreover you can  find a lot of implementations here http://www.borgelt.net/fpm.html and here  http://fimi.ua.ac.be/src/ currently the best one should be FP-Growth

**Comment by faithefeng** [comment]
I apply this Package on a database of 2MB. The trouble is it takes about several hours, is it possible to speed up this implementation in Python of Apriori?

**Comment by asaini** [comment]
@faithefeng, @pritishyuvraj : Have you tried using FP-Growth?

**Comment by bsutherland** [comment]
This implementation seems to be based on the original paper on Apriori. There are several later papers which describe major optimizations to the algorithm. For example, this one speeds up the 2-itemset generation step (generally the slowest step) greatly: http://user.it.uu.se/~kostis/Teaching/DM-01/Handouts/PCY.pdf
